### ISSUE TITLE
Frontmatter support

### ISSUE THREAD

**Issue by amio** [amio/eloc#6]
A much better way to config.

The only issue is the bundle size. `js-yaml` costs 171.9 kB, `yaml` costs 93.1 kB, while the `markdown-deck` is 93.7 kB now.

Or maybe go with an in-house naive front-matter implementation. It's just a few configurations, won't need full featured yaml parser.

**Comment by zthxxx** [comment]
maybe make frontmatter only parse a subset of yaml, 

such as only contains string, number and list, and without nested:

```yaml
title: xxxxxxx
date: 2020-03-24 11:21
tags: [OOXX, XXOO]
categories: 
  - xxxxx
  - sub-xxxx
```

so that we can minimize the cost to implement a parser
